Polymer/polymer-modulizer

- src/convert-package.ts
I hit the same error when trying to modulize the Polymer core library. It seems that the source is not generated, but the file was not generated as well. Therefore add a safe-guard that if the file actually exists we remove the file.
I did not remove the else-clause as I was uncertain in what case it was actually used, thus a safe-guard seemed a safer approach.
Fixes #179
> Fix error thrown when unlinking an non-existing file

- src/base-converter.ts
- src/conversion-metadata.ts
- src/document-converter.ts
- src/js-module.ts
- src/test/analysis-converter_test.ts
- src/tools/test-polymer.ts
- src/url-converter.ts
*A part of #217: "Refactor ProjectConverter to Fix URL Handling"*
*First PR! Start here!*
Previously, `outputs` contained a mishmash of url. Some used the old bower file location, some used the new npm file location, and some were manually constructed. This has caused cache misses and slower conversions (and annoying bugs as I've been poking around and refactoring).
This PR fixes all of these issues by always keying to the OriginalDocumentUrl, along with some naming clarifications.
> [ProjectConverter] Fix outputs keying to prevent cache missing, duplicates

- bin/modulizer.js
- src/cli/command-package.ts
- src/cli/command-workspace.ts
- src/cli/index.ts
- src/convert-package.ts
- src/convert-workspace.ts
- src/test/analysis-converter_test.ts
- src/tools/checkpoint-polymer.ts
- src/tools/test-polymer.ts
- src/util.ts
- yarn.lock
*A part of #217: "Refactor ProjectConverter to Fix URL Handling"*
*Builds off of #216: "Fix outputs keying to prevent cache missing, duplicates"*
This PR cleans up some of the CLI logic and partially-moved file structure.
- some bug fixes around path resolution for paths provided by the CLI
- The main CLI entrypoint is moved into the `cli/` subdirectory with the other CLI logic
- inDir & outDir are now always resolved by the time they get to the `convert()` method.
- workspace conversion runs off the polymer-workspaces list of repos, instead of a directory scan
> [ProjectConverter] Clean up CLI setup/layout

- src/analysis-converter.ts
- src/base-converter.ts
- src/conversion-metadata.ts
- src/document-converter.ts
- src/js-module.ts
- src/test/analysis-converter_test.ts
- src/test/urls/util_test.ts
- src/tools/test-polymer.ts
- src/urls/types.ts
- src/urls/util.ts
- src/workspace-converter.ts
*A part of #217: "Refactor ProjectConverter to Fix URL Handling"*
*Builds off of #219: "[ProjectConverter] Clean up CLI setup/layout"*
This PR sets up the larger refactoring work of #217 by cleaning up some of the URL handling logic.
- No behavior changes 
- Temporarily move url-converter logic into `urls/util.ts`, in preparation for final move to UrlHandlers
- Break out types into separate `urls/types.ts` file, in preparation for additional url-related types
> [ProjectConverter] Clean up url-converter logic/layout

- src/cli/command-package.ts
- src/cli/command-workspace.ts
- src/cli/index.ts
- src/conversion-settings.ts
- src/document-converter.ts
- src/urls/package-url-handler.ts
- src/urls/url-handler.ts
- src/urls/workspace-url-handler.ts
*A part of #217: "Refactor ProjectConverter to Fix URL Handling"*
*Builds off of #224: "[ProjectConverter] Refactor BaseConverter into UrlHandler, ProjectConverter"*
Adds the CLI option `--import-by-name` to format npm package imports using names instead of paths.
> Add option to import npm packages by name

- package.json
- src/manifest-converter.ts
- src/test/unit/project-converter_test.ts
Deduplicated warnings for dependencies.
Removed the `warn` flag since it wasn't utilized anywhere.
Ran formatter.
Cleaned up globs into a lookup. (Separated this in a commit for easy revert if you don't like it)
If you would like `warn` re-added, what would its function be? At this point it seems like it would be forcing display of the warning regardless of the de-duplication.
>  Fix: Dedupe dependency warnings

- custom_typings/spdx-license-list.d.ts
- fixtures/packages/iron-icon/expected/package.json
- fixtures/packages/paper-button/expected/package.json
- fixtures/packages/polymer/expected/package.json
- package.json
- src/manifest-converter.ts
Fixes #185 
Handles the polymer LICENSE URL => BSD-3-Clause
Warns user if the current license in bower is not a valid SPDX license. Perhaps further improvement could suggest the closest license?
**Open Questions:**
- How should we handle an existing `package.json` and `bower.json`, both having different licenses specified?
- Should we warn if no license has been specified or default to something like `Unlicense`?
- Would it be better to have a tedium process change the license on all PolymerElements from the Polymer License Url to BSD-3-Clause instead of having a custom logic branch built in here?
> New: Check for SPDX license

- .gitignore
- .vscode/launch.json
This is a generic .vscode/launch.json configuration for vscode line-by-line debugging. It can be modified to test any specific arguments, but should stay generic within git.
> Add .vscode/launch file for vscode debugging

- src/document-converter.ts
- src/js-module.ts
- src/project-converter.ts
- src/test/unit/project-converter_test.ts
Fixes #200 
This is a pretty conservative version of a fix. It only effects files that only have a script tag that points to what would be name of the converted output file. We can extend this to eliminate wrappers that point to other files, but those don't always result in a file being overwritten like this case. We should also probably add detection of overwrites in general.
> Delete HTML files that are simple wrappers on external scripts

- src/tools/update-fixtures.ts
Also makes update-fixtures script set a non-zero exit code if any of the fixtures fail to setup.
> Support specifying a git branch when setting up test fixtures.

- custom_typings/ast-types.d.ts
- fixtures/packages/paper-button/expected/test/paper-button.html
- src/cli/command-workspace.ts
- src/document-converter.ts
- src/passes/add-a11y-suite-if-used.ts
- src/project-converter.ts
- src/publish-workspace.ts
- src/push-workspace.ts
- src/test/unit/project-converter_test.ts
- src/urls/package-url-handler.ts
- src/urls/url-handler.ts
- src/urls/workspace-url-handler.ts
Related to https://github.com/Polymer/web-component-tester/pull/665
`a11ySuite` is now a module, so we need to import references to it directly. This creates an explicit import `a11ySuite` vs. the more convoluted ESM->ESM exporting via the window object.
> Add import references to a11ySuite in tests

- bin/modulizer.js
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
We get this when we try to run all Polymer repos together.
> increase process memory size

- dependency-map.json
We still use this for modulization. Working on a patch to use the being-created version on all packages undergoing conversion.
> update the dependency map for the latest release

- src/test-workspace.ts
- src/util.ts
When running modulizer on a giant batch of elements, currently we need to wait for the entire batch to complete before getting any error/success messages.
> run workspace tests repo-by-repo

- src/publish-workspace.ts
- src/push-workspace.ts
Right now they succeed and fail silently. Ultimately these should probably function like our tests, running and logging together serially. But that would require a coordinated change to polymer-workspaces, and right now this is fine.
> report push & publish results

- package-lock.json
- package.json
- src/conversion-settings.ts
- src/convert-package.ts
- src/convert-workspace.ts
- src/document-converter.ts
- src/project-converter.ts
- src/special-casing.ts
- src/test/unit/project-converter_test.ts
- src/urls/package-url-handler.ts
- src/urls/url-handler.ts
- src/urls/util.ts
- src/urls/workspace-url-handler.ts
Fixes #306
Background: Polymer Analyzer v3 includes a major change to how urls are handled. Instead of being package-relative, they are now absolute to the file system. polymer-modulizer was built to work with package-relative urls, and gets a lot of benefits from that system over complete absolute 
urls (easier to check against, manipulate, etc). 
This PR updates the existing calls to `getDocumentUrl()` to handle the analyzer's new url format and get all the analyzer updates from the last few months. We now need to keep a reference to the analyzer during conversion itself, but it fits well into our existing concept of a conversion UrlHandler.
Long-term, we could consider doing the work to move to use the analyzer's absolute url format internally as well to take advantage of the …
> update analyzer to v3.0.0-pre.10, typescript

- src/convert-package.ts
- src/convert-workspace.ts
We have polymer-specific override mappings that were affected by the analyzer 3.0.0 upgrade, but were only just caught when converting actually Polymer & Polymer elements.
> fix overrides file map url resolution

- src/cli/command-workspace.ts
Fixes #359 
Passing `addImportPath` ala [`command-package.ts`](https://github.com/Polymer/polymer-modulizer/blob/master/src/cli/command-package.ts#L99)
> pass add-import-path to conversion

- src/travis-config.ts
Yes, a travis.yml can exist and be empty. Because why not! 
**ex:** https://github.com/PolymerElements/app-media/blob/master/.travis.yml
**DefinitelyTyped fix here:** https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24385
> handle bad travis.yml

- src/document-converter.ts
- src/test/unit/project-converter_test.ts
top-level HTML documents can't import things by name, since "bare-module specifiers" in HTML (ex: `<script src="@polymer/polymer/foobar.html">`) are just impossible to differentiate from relative URLs  (ex: `<script src="./@polymer/polymer/foobar.html">`).
This PR forces all HTML imports to use paths, while still allowing JS module imports to use bare module specifiers (import dependencies by name). 
With this change, tests now pass when elements are converted with `--import-style name`.
> Force paths for top level html

- src/cli/command-package.ts
- src/cli/command-workspace.ts
- src/cli/index.ts
- src/cli/util.ts
- src/package-manifest.ts
- src/package-scanner.ts
- src/project-scanner.ts
- src/test-workspace.ts
- src/test/unit/cli/util_test.ts
- src/test/unit/package-manifest_test.ts
- src/test/unit/project-converter_test.ts
It's now possible to add custom dependency mappings for conversion.
Example:
```
modulizer --repo XXX YYY ZZZ --dependency-mapping old-name,new-name,^2.0.0 prism,prismjs,^1.0.0
```
> add ability to map custom bower->npm dependencies

- dependency-map.json
- fixtures/packages/iron-icon/expected/package.json
- fixtures/packages/paper-button/expected/package.json
- fixtures/packages/polymer/expected/package.json
- src/test/unit/package-manifest_test.ts
- After each release, we update the dependency map to the new released version tag
- We've decided to remove the leading `^` from our own dependencies going forward, so that we can test breaking changes under the `next` tag before sharing them with our users.
- This PR also adds some previously unmapped dependencies
> update dependency map for pre.12, unmapped 3rd party dependencies

- src/conversion-manifest.ts
- src/document-converter.ts
- src/document-processor.ts
- src/document-scanner.ts
- src/package-scanner.ts
- src/project-scanner.ts
- src/test/unit/project-converter_test.ts
Makes the document scanning vs converting process a bit easier to follow.
no-op change.
> Separate out document conversion from scanning.

- fixtures/packages/polymer/expected/lib/elements/array-selector.js
- fixtures/packages/polymer/expected/lib/elements/dom-module.js
- fixtures/packages/polymer/expected/lib/legacy/class.js
- fixtures/packages/polymer/expected/lib/legacy/legacy-element-mixin.js
- fixtures/packages/polymer/expected/lib/legacy/mutable-data-behavior.js
- fixtures/packages/polymer/expected/lib/legacy/polymer-fn.js
- fixtures/packages/polymer/expected/lib/legacy/polymer.dom.js
- fixtures/packages/polymer/expected/lib/legacy/templatizer-behavior.js
- fixtures/packages/polymer/expected/lib/mixins/dir-mixin.js
- fixtures/packages/polymer/expected/lib/mixins/disable-upgrade-mixin.js
- fixtures/packages/polymer/expected/lib/mixins/element-mixin.js
- fixtures/packages/polymer/expected/lib/mixins/gesture-event-listeners.js
- fixtures/packages/polymer/expected/lib/mixins/mutable-data.js
- fixtures/packages/polymer/expected/lib/mixins/properties-changed.js
- fixtures/packages/polymer/expected/lib/mixins/properties-mixin.js
- fixtures/packages/polymer/expected/lib/mixins/property-accessors.js
- fixtures/packages/polymer/expected/lib/mixins/property-effects.js
- fixtures/packages/polymer/expected/lib/mixins/template-stamp.js
- fixtures/packages/polymer/expected/lib/utils/flush.js
- fixtures/packages/polymer/expected/lib/utils/gestures.js
- fixtures/packages/polymer/expected/lib/utils/html-tag.js
- fixtures/packages/polymer/expected/lib/utils/import-href.js
- fixtures/packages/polymer/expected/lib/utils/mixin.js
- fixtures/packages/polymer/expected/lib/utils/path.js
- fixtures/packages/polymer/expected/lib/utils/settings.js
- fixtures/packages/polymer/expected/polymer-element.js
- fixtures/packages/polymer/expected/polymer.js
- src/passes/rewrite-namespace-exports.ts
- src/test/unit/project-converter_test.ts
Analyzing and linting polymer 3 sources was having lots of issues due to load-bearing-comments being missing.
> Preserve comments in rewrite namespace exports pass.

- .vscode/launch.json
- src/cli/command-package.ts
- src/cli/index.ts
- src/conversion-settings.ts
- src/convert-package.ts
- src/urls/package-url-handler.ts
Fixes #206
We seem to have been ignoring the type of project we are trying to modulize. This affects whether it's a relative path out of the package or into `node_modules`. This can be set via the `--package-type` flag which defaults to `element`.
I had it as a mandatory flag where it would ask you to choose between element and application but I changed my mind because I personally didn't like having to type it in every time. LMK if I should bring it back.
CC @notwaldorf
> Package type

- fixtures/packages/polymer/expected/lib/mixins/element-mixin.js
- fixtures/packages/polymer/expected/lib/utils/array-splice.js
- fixtures/packages/polymer/expected/lib/utils/async.js
- fixtures/packages/polymer/expected/lib/utils/case-map.js
- fixtures/packages/polymer/expected/lib/utils/gestures.js
- fixtures/packages/polymer/expected/lib/utils/path.js
- fixtures/packages/polymer/expected/lib/utils/render-status.js
- fixtures/packages/polymer/expected/lib/utils/resolve-url.js
- fixtures/packages/polymer/expected/lib/utils/style-gather.js
- fixtures/packages/polymer/expected/lib/utils/templatize.js
- src/passes/rewrite-namespace-exports.ts
- src/test/unit/project-converter_test.ts
Fixes https://github.com/Polymer/polymer-modulizer/issues/398
Can confirm that this saves many hundreds of lines of comments from Polymer core.
Probably much less from other projects, as Polymer core uses a _lot_ of namespaces.
> Handle namespace export comments better.

- fixtures/packages/iron-icon/expected/demo/index.html
- fixtures/packages/paper-button/expected/demo/index.html
- fixtures/packages/paper-button/expected/paper-button.js
- fixtures/packages/polymer/expected/test/smoke/style-props/src/elements-defaults.js
- fixtures/packages/polymer/expected/test/smoke/style-props/src/settings.js
- fixtures/packages/polymer/expected/test/unit/custom-style-import.js
- fixtures/packages/polymer/expected/test/unit/custom-style.html
- fixtures/packages/polymer/expected/test/unit/shady-unscoped-style-import.js
- fixtures/packages/polymer/expected/test/unit/styling-import-shared-styles.js
- fixtures/packages/polymer/expected/test/unit/sub/resolveurl-elements.js
- fixtures/packages/polymer/expected/test/unit/sub/style-import.js
- src/document-util.ts
- src/test/unit/project-converter_test.ts
Fixes #410 by applying the change from Polymer/polymer#5210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/polymer-modulizer/411)
> Avoid using nested templates when setting innerHTML

- dependency-map.json
- fixtures/packages/iron-icon/expected/package.json
- fixtures/packages/paper-button/expected/package.json
- fixtures/packages/polymer/expected/package.json
- src/package-manifest.ts
`wct-browser-legacy` 1.0.1 no longer depends on the `webcomponentsjs` 1.x
See also Polymer/tools#397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/polymer-modulizer/442)
> Bump wct-browser-legacy mapping, remove webcomponentsjs resolution
