Polymer/polymer-modulizer

README.md

I tried to do an install and got confused: a monica story.

embetter the installation instructions

---

src/base-converter.ts
src/document-converter.ts
src/test/analysis-converter_test.ts

Fixes https://github.com/Polymer/polymer-modulizer/issues/191

Preserve comments in HTML->JS transform.

---

CHANGELOG.md

v0.3.0 prerelease

---

src/test-workspace.ts

See #254:
> There are a few issues uncovered with running `yarn install --flat` in a workspace:
> 
> 1. Yarn has a bug where the git hash of a locally referenced dependency (that's also been converted) is read as the package "version", causing errors inside of yarn ("83c19296e1cc615c224df685c497a8e5e38dcdf5 is not a valid version") .
> 2. The new, desired post-conversion version is written to each package.json, which can cause conflicts when installing (ex: `can't flatten semver ranges "3.0.0-pre.1" & "3.0.0-pre.2").
Reverting to use `npm install` now, but we should fix this so that we have proper support for yarn.

use npm install instead of yarn install

---

.travis.yml
bin/modulizer.js
package.json

Prints a message if the user doesn't have the minimum version of Node to run this tool.

New: Check Node version before run

---

package.json

update polymer-workspaces v2.1.0

---

docs/polymer-3-element-status.md

Based on comments from https://github.com/Polymer/polymer-modulizer/pull/271
/cc @stramel

clarify 3.0 support table headers

---

bin/modulizer.js
package-lock.json
package.json
src/cli/index.ts
src/publish-workspace.ts
src/push-workspace.ts
src/test-workspace.ts
src/test/fixtures/fixtures_test.ts

@FredKSchott Fixes #288 
Also, ran format.

Fix: version

---

.appveyor.yml
.gitattributes
package-lock.json
package.json
src/document-converter.ts
src/document-util.ts
src/manifest-converter.ts
src/publish-workspace.ts
src/push-workspace.ts
src/test-workspace.ts
src/test/fixtures/fixtures_test.ts
src/test/unit/project-converter_test.ts
src/test/unit/urls/util_test.ts
test/run-mocha.sh

Start of #236 Possibly fixes? Tests seem to pass?
Link to passing tests: https://ci.appveyor.com/project/stramel/polymer-modulizer/build/26

New: Add Windows testing support

---

docs/polymer-3-element-status.md

Lots of new passing elements in the paper-* elements collection!
This is for batch pre.8 (not yet released)

Update element test results for latest batch

---

src/document-converter.ts

add test-helpers as a known js file

---

src/document-util.ts
src/test/unit/project-converter_test.ts

fix multiple js comments in a html comment

---

dependency-map.json
fixtures/packages/iron-icon/test.js
fixtures/packages/paper-button/test.js

Fixes marked-element tests. ~Something else is also messing with prism-element~ fixed.

add missing deps marked and prism

---

README.md

@fredkschott can you add the proper badge status Id? I couldn't seem to find it. 
Should be the final bits of #236 
Made PR on my phone so let me know if something is wrong
Closes #236

New: Add Windows Build badge

---

docs/polymer-3-element-status.md

4 now green; lots more passing tests

updated passing tests

---

docs/polymer-3-element-status.md

Continuation of #330. (I forgot to hit ⌘+S)
10 more passing elements (14 if you add the 4 from #330) 
Lots more passing tests

Update passing elements

---

src/test/fixtures/fixtures_test.ts

Update fixtures_test.ts to use `compareContent: true`

---

fixtures/packages/polymer/expected/test/unit/shady-dynamic.html
src/convert-package.ts
src/convert-workspace.ts
src/document-converter.ts
src/passes/remove-toplevel-use-strict.ts
src/passes/rewrite-toplevel-this.ts
src/test/unit/project-converter_test.ts

Fix: Remove top-level use-strict statement

---

src/convert-package.ts
src/convert-workspace.ts

delete bower after generating package.json

---

fixtures/packages/iron-icon/expected/.gitignore
fixtures/packages/paper-button/expected/.gitignore
fixtures/packages/polymer/expected/.gitignore
src/convert-package.ts
src/convert-workspace.ts
src/gitignore.ts

Add node_modules to gitignore

---

.vscode/tasks.json
package-lock.json
package.json
src/test/unit/package-manifest_test.ts
src/test/unit/util.ts
test/run-mocha.sh

Expected warnings should be captured and asserted on, not logged.
Also use much faster test:watch implementation.

Reduce noise in tests.

---

src/passes/rewrite-namespace-exports.ts
src/test/unit/project-converter_test.ts

this.x = assignments in namespace functions make properties mutable

---

src/cli/command-workspace.ts
src/test-workspace.ts

Important so that we don't need to edit source to test our elements with different flags / on only Chrome, and can handle passing different --module-resolution flags.

pass wct flags to test

---

CHANGELOG.md
src/cli/index.ts
src/convert-package.ts
src/package-scanner.ts
src/project-converter.ts

This should have happened in #372. Doesn't seem like there was any documentation for `includes` other than comments in the code, so I haven't updated anything surrounding that.

Remove `include` CLI flag.

---

src/cli/command-workspace.ts

Do we have tests for workspace mode? I'm not sure where I would write a test for this.

Pass `exclude` arguments to the workspace converter.

---

docs/polymer-3-element-status.md

I ran only the elements that were failing from last run. I have gone and fixed some failing elements and have some PRs open. I have marked these elements with open PRs as passing.

Updated element status

---

dependency-map.json
fixtures/packages/iron-icon/expected/package.json
fixtures/packages/paper-button/expected/package.json
fixtures/packages/polymer/expected/package.json
src/package-manifest.ts

Submitting this to ensure the tests pass in the CI so we can rely on it.
@e111077 Feel free to close in favor of your PR. I will leave a branch there though, currently working on converting Vaadin components using this branch of the modulizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/polymer-modulizer/413)

Update webcomponentsjs to 2.0.0-beta.2

---

src/passes/rewrite-namespace-this-references.ts
src/test/unit/project-converter_test.ts

Rewrite NS object references that don't reference members to undefined.

---

dependency-map.json
docs/polymer-3-element-status.md
fixtures/packages/iron-icon/expected/package.json
fixtures/packages/paper-button/expected/package.json
fixtures/packages/polymer/expected/package.json

I only ran tests on all browsers for a subset of elements. Ran all tests on chrome to check this release

bump version and update passing tests

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/polymer-modulizer/419)

Update output snippet to use html tag

---

dependency-map.json

add missing dep to depmap re: app-media

add webrtc-adapter

---

fixtures/packages/iron-icon/expected/.travis.yml
fixtures/packages/paper-button/expected/.travis.yml
fixtures/packages/polymer/expected/.travis.yml
src/travis-config.ts

this is so that we can include these in master but not in the modulzied files.

remove travis type and format checks
